<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
    <PackageIcon>app_icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <COMReference Include="NetFwTypeLib">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>58fbcf7c-e7a9-467c-80b3-fc65e8fcca08</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="app_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="InputSimulator" Version="1.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app_icon.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="app_icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <Import Project="..\PCTimeLinitShared\PCTimeLinitShared.projitems" Label="Shared" />

</Project>
